using System.Collections.Generic;

namespace Klavogonki
{
    public static class CarsConstants
    {
        public static readonly Dictionary<int, string> Cars = new Dictionary<int, string>
            {
                {1, "ЗАЗ 965"},
                {3, "Беларус 922"},
                {24, "Caterpillar 247B"},
                {40, "Chevrolet EN-V"},
                {26, "Volkswagen Beetle"},
                {19, "Duesenberg Speedster"},
                {35, "Ferrari 250 Testa Rossa"},
                {31, "Трамвай"},
                {2, "ВАЗ 2104"},
                {38, "УАЗ 3151"},
                {5, "Fiat Strada"},
                {4, "Peugeot Boxer"},
                {6, "Hummer H3"},
                {41, "LM Rally Fighter"},
                {7, "Daewoo Matiz"},
                {8, "Ford Focus Mk2"},
                {29, "Renault Megane"},
                {9, "Toyota Land Cruiser"},
                {23, "Smart Fortwo"},
                {37, "Nissan Round Box"},
                {34, "Chevrolet Orlando"},
                {10, "Volkswagen Passat B3"},
                {11, "Mitsubishi Lancer X"},
                {12, "BMW X6"},
                {30, "Subaru Tourer"},
                {28, "Citroen Hypnos"},
                {33, "Bugatti Galibier"},
                {13, "Audi TT"},
                {16, "Lamborghini Murcielago"},
                {27, "Dodge Viper"},
                {15, "Болид F1"},
                {14, "Bugatti Veyron"},
                {36, "Ferrari Zobin"},
                {22, "Ferrari FX Concept"},
                {17, "Бэтмобиль"},
                {39, "Danny Chhang Concept"},
                {18, "Аэроглиссер"},
                {25, "SS-1"},
                {20, "НЛО"},
                {32, "Инсекатор"},
                {42, "SS-X"},
                {43, "Porsche Cayenne S"},
                {44, "Honda CBR 1000RR"},
                {45, "Каравелла"},
                {1000, "BMW M6"},
                {1001, "Hennessey Venom GT1"},
                {1002, "DeLorean Time Machine"},
                {1003, "Submarine"},
                {1004, "Honda CBR 1000RR"},
                {1005, "Трамвай"},
                {1006, "Motorcity Europe MC1"},
                {1007, "Инсекатор"},
                {1008, "Mercedes-Benz SL 600"},
                {1009, "Porsche Cayenne S"},
                {1010, "Pagani Zonda R"},
                {1011, "Бэтпод"},
                {1012, "ЗИС-155"},
                {1013, "Volkswagen Corrado"},
                {1014, "Volkswagen Corrado"},
                {1015, "Red Eagle"},
                {1016, "ΙΧΘΥΣ"},
                {1017, "Parasailing"},
                {1018, "Дракон"},
                {1019, "Каравелла"},
                {1020, "N-Bar"},
                {1021, "ДУ-49"},
                {1022, "Ducati 848 2010"},
                {1023, "Tumbler"},
                {1024, "Ferrari F12"}
            };

    }
}
